# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "api/"
    schedule:
      interval: "weekly"
    target-branch: main
    ignore:
      # 更新頻度がﾔﾊﾞｲのでminorバージョンアップ毎に更新
      - dependency-name: github.com/aws/aws-sdk-go
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "client/"
    schedule:
      interval: "weekly"
    target-branch: main
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10
