// Code generated by goagen v1.5.13, DO NOT EDIT.
//
// API "docker_goa_next": users Resource Client
//
// Command:
// $ goagen
// --design=github.com/kod-source/docker-goa-next/webapi/design
// --out=$(GOPATH)/src/app/webapi
// --version=v1.5.13

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetCurrentUserUsersPath computes a request path to the get_current_user action of users.
func GetCurrentUserUsersPath() string {
	return fmt.Sprintf("/current_user")
}

// ログインしているユーザーの情報を取得する
func (c *Client) GetCurrentUserUsers(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetCurrentUserUsersRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetCurrentUserUsersRequest create the request corresponding to the get_current_user action endpoint of the users resource.
func (c *Client) NewGetCurrentUserUsersRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// SignUpUsersPayload is the users sign_up action payload.
type SignUpUsersPayload struct {
	// メール
	Email string `form:"email" json:"email" yaml:"email" xml:"email"`
	// 名前
	Name string `form:"name" json:"name" yaml:"name" xml:"name"`
	// パスワード
	Password string `form:"password" json:"password" yaml:"password" xml:"password"`
}

// SignUpUsersPath computes a request path to the sign_up action of users.
func SignUpUsersPath() string {
	return fmt.Sprintf("/sign_up")
}

// サインアップ
func (c *Client) SignUpUsers(ctx context.Context, path string, payload *SignUpUsersPayload, contentType string) (*http.Response, error) {
	req, err := c.NewSignUpUsersRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSignUpUsersRequest create the request corresponding to the sign_up action endpoint of the users resource.
func (c *Client) NewSignUpUsersRequest(ctx context.Context, path string, payload *SignUpUsersPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
