// Code generated by goagen v1.5.13, DO NOT EDIT.
//
// API "docker_goa_next": Application User Types
//
// Command:
// $ goagen
// --design=github.com/kod-source/docker-goa-next/webapi/design
// --out=/Users/horikoudai/Documents/ProgrammingLearning/docker-goa-next/api/webapi
// --version=v1.5.13

package app
