version: '3.7'
services:
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    container_name: db-goa
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db-goa-next:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      # target: dev
    environment:
      - END_POINT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - MYSQL_HOST
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    environment:
      - NEXT_PUBLIC_END_POINT
    tty: true
    ports:
      - '8080:3000'
    depends_on:
      - api

  schemaspy:
    build:
      context: .
      dockerfile: ./docker/schemaspy/Dockerfile
    platform: linux/x86_64
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./api/schemaspy:/output
      - ./docker/schemaspy/config/schemaspy.properties:/app/schemaspy.properties:ro
    depends_on:
      - db

  nginx_schemaspy:
    image: nginx:1.19.5-alpine
    container_name: 'nginx_schemaspy'
    ports:
      - '8083:80'
    volumes:
      - ./api/schemaspy:/usr/share/nginx/html:ro
