version: '3.7'
services:
  client:
    build:
      context: ./docker/client/
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./client:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - '8080:3000'
