import { Button } from '@mui/material';
import { DateTime } from 'luxon';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useContext } from 'react';
import styles from '../styles/Home.module.css';
import { AppContext } from './_app';

const Home: NextPage = () => {
  const { user } = useContext(AppContext);
  const router = useRouter();

  const logout = () => {
    localStorage.removeItem('token');
    router.push('/login');
  };

  if (!user) {
    return <p>Loading</p>;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Top Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='text-right m-2'>
        <Button onClick={() => logout()}>ログアウト</Button>
      </div>
      <div className='text-center text-red-700'>
        <h1>トjップページ</h1>
        <div>
          <p>ID : {user.id}</p>
          <p>ユーザー名 : {user.name}</p>
          <p>メールアドレス : {user.email}</p>
          <p>
            作成日 :{' '}
            {DateTime.fromJSDate(user.createdAt).toFormat('yyyy年MM月dd日')}
          </p>
        </div>
      </div>
    </div>
  );
};

export default Home;
