import { NextPage } from 'next';
import Head from 'next/head';

const Message: NextPage = () => {
  return (
    <>
      <Head>
        <title>Message</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <div>
          <h2>メッセージ</h2>
          <p>プラス</p>
        </div>
        <div>{/* メッセージ一覧 */}</div>
        <div>{/* viewを表示 */}</div>
      </div>
    </>
  );
};

export default Message;
