name: api-test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: start MySQL
        run: sudo systemctl start mysql.service

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: move api directory
        run: cd api/

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_LOCAL_PORT: 13306
          MYSQL_LOCAL_HOST: 127.0.0.1
