name: api-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: start MySQL
        run: sudo systemctl start mysql.service

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...
        working-directory: ./api

      - name: Test
        run: go test -v ./...
        working-directory: ./api
        env:
          MYSQL_DATABASE: db
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_LOCAL_PORT: 3306
          MYSQL_LOCAL_HOST: 127.0.0.1
